# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\tlyngen\source\repos\expensieve\ui\qt\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(522, 440)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBoxSummary = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxSummary.setGeometry(QtCore.QRect(10, 10, 191, 91))
        self.groupBoxSummary.setObjectName("groupBoxSummary")
        self.labelTotalExpenses = QtWidgets.QLabel(self.groupBoxSummary)
        self.labelTotalExpenses.setGeometry(QtCore.QRect(10, 20, 91, 16))
        self.labelTotalExpenses.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelTotalExpenses.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelTotalExpenses.setObjectName("labelTotalExpenses")
        self.labelOwedToMe = QtWidgets.QLabel(self.groupBoxSummary)
        self.labelOwedToMe.setGeometry(QtCore.QRect(10, 40, 91, 16))
        self.labelOwedToMe.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.labelOwedToMe.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelOwedToMe.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelOwedToMe.setObjectName("labelOwedToMe")
        self.labelOwedToOthers = QtWidgets.QLabel(self.groupBoxSummary)
        self.labelOwedToOthers.setGeometry(QtCore.QRect(10, 60, 91, 16))
        self.labelOwedToOthers.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelOwedToOthers.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelOwedToOthers.setObjectName("labelOwedToOthers")
        self.labelTotalExpensesValue = QtWidgets.QLabel(self.groupBoxSummary)
        self.labelTotalExpensesValue.setGeometry(QtCore.QRect(110, 20, 71, 16))
        self.labelTotalExpensesValue.setObjectName("labelTotalExpensesValue")
        self.labellOwedToMeValue = QtWidgets.QLabel(self.groupBoxSummary)
        self.labellOwedToMeValue.setGeometry(QtCore.QRect(110, 40, 71, 16))
        self.labellOwedToMeValue.setObjectName("labellOwedToMeValue")
        self.labellOwedToOthersValue = QtWidgets.QLabel(self.groupBoxSummary)
        self.labellOwedToOthersValue.setGeometry(QtCore.QRect(110, 60, 71, 16))
        self.labellOwedToOthersValue.setObjectName("labellOwedToOthersValue")
        self.pushButtonNewExpense = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonNewExpense.setGeometry(QtCore.QRect(100, 110, 101, 31))
        self.pushButtonNewExpense.setAutoDefault(True)
        self.pushButtonNewExpense.setObjectName("pushButtonNewExpense")
        self.groupBoxExpenses = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxExpenses.setGeometry(QtCore.QRect(210, 10, 301, 411))
        self.groupBoxExpenses.setObjectName("groupBoxExpenses")
        self.listWidgetExpenses = QtWidgets.QListWidget(self.groupBoxExpenses)
        self.listWidgetExpenses.setGeometry(QtCore.QRect(10, 20, 281, 381))
        self.listWidgetExpenses.setObjectName("listWidgetExpenses")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.pushButtonNewExpense, self.listWidgetExpenses)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Expensieve"))
        self.groupBoxSummary.setTitle(_translate("MainWindow", "Summary"))
        self.labelTotalExpenses.setText(_translate("MainWindow", "Total Expenses:"))
        self.labelOwedToMe.setText(_translate("MainWindow", "Owed to me:"))
        self.labelOwedToOthers.setText(_translate("MainWindow", "Owed to others:"))
        self.labelTotalExpensesValue.setText(_translate("MainWindow", "0"))
        self.labellOwedToMeValue.setText(_translate("MainWindow", "0"))
        self.labellOwedToOthersValue.setText(_translate("MainWindow", "0"))
        self.pushButtonNewExpense.setText(_translate("MainWindow", "New Expense"))
        self.groupBoxExpenses.setTitle(_translate("MainWindow", "Expenses"))
