# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\tlyngen\source\repos\expensieve\ui\dialog_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogLogin(object):
    def setupUi(self, DialogLogin):
        DialogLogin.setObjectName("DialogLogin")
        DialogLogin.resize(217, 117)
        DialogLogin.setModal(True)
        self.pushButtonLogin = QtWidgets.QPushButton(DialogLogin)
        self.pushButtonLogin.setGeometry(QtCore.QRect(130, 80, 75, 23))
        self.pushButtonLogin.setObjectName("pushButtonLogin")
        self.pushButtonCreate = QtWidgets.QPushButton(DialogLogin)
        self.pushButtonCreate.setGeometry(QtCore.QRect(50, 80, 75, 23))
        self.pushButtonCreate.setObjectName("pushButtonCreate")
        self.lineEditUserName = QtWidgets.QLineEdit(DialogLogin)
        self.lineEditUserName.setGeometry(QtCore.QRect(90, 10, 113, 20))
        self.lineEditUserName.setObjectName("lineEditUserName")
        self.lineEditPassword = QtWidgets.QLineEdit(DialogLogin)
        self.lineEditPassword.setGeometry(QtCore.QRect(90, 40, 113, 20))
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.labelUserName = QtWidgets.QLabel(DialogLogin)
        self.labelUserName.setGeometry(QtCore.QRect(20, 10, 61, 20))
        self.labelUserName.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelUserName.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelUserName.setObjectName("labelUserName")
        self.labelPassword = QtWidgets.QLabel(DialogLogin)
        self.labelPassword.setGeometry(QtCore.QRect(20, 40, 61, 20))
        self.labelPassword.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelPassword.setObjectName("labelPassword")

        self.retranslateUi(DialogLogin)
        self.pushButtonLogin.clicked.connect(DialogLogin.accept) # type: ignore
        self.pushButtonCreate.clicked.connect(DialogLogin.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DialogLogin)

    def retranslateUi(self, DialogLogin):
        _translate = QtCore.QCoreApplication.translate
        DialogLogin.setWindowTitle(_translate("DialogLogin", "Login"))
        self.pushButtonLogin.setText(_translate("DialogLogin", "Login"))
        self.pushButtonCreate.setText(_translate("DialogLogin", "Create"))
        self.labelUserName.setText(_translate("DialogLogin", "User name:"))
        self.labelPassword.setText(_translate("DialogLogin", "Password:"))
