# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\tlyngen\source\repos\expensieve\ui\dialog_expense.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogExpense(object):
    def setupUi(self, DialogExpense):
        DialogExpense.setObjectName("DialogExpense")
        DialogExpense.resize(217, 117)
        DialogExpense.setModal(True)
        self.pushButtonSave = QtWidgets.QPushButton(DialogExpense)
        self.pushButtonSave.setGeometry(QtCore.QRect(40, 80, 75, 23))
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.lineEditExpenseName = QtWidgets.QLineEdit(DialogExpense)
        self.lineEditExpenseName.setGeometry(QtCore.QRect(90, 10, 113, 20))
        self.lineEditExpenseName.setObjectName("lineEditExpenseName")
        self.lineEditExpenseAmount = QtWidgets.QLineEdit(DialogExpense)
        self.lineEditExpenseAmount.setGeometry(QtCore.QRect(90, 40, 113, 20))
        self.lineEditExpenseAmount.setObjectName("lineEditExpenseAmount")
        self.labelExpenseName = QtWidgets.QLabel(DialogExpense)
        self.labelExpenseName.setGeometry(QtCore.QRect(20, 10, 61, 20))
        self.labelExpenseName.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelExpenseName.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelExpenseName.setObjectName("labelExpenseName")
        self.labelExpenseAmount = QtWidgets.QLabel(DialogExpense)
        self.labelExpenseAmount.setGeometry(QtCore.QRect(20, 40, 61, 20))
        self.labelExpenseAmount.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelExpenseAmount.setObjectName("labelExpenseAmount")
        self.pushButtonCancel = QtWidgets.QPushButton(DialogExpense)
        self.pushButtonCancel.setGeometry(QtCore.QRect(130, 80, 75, 23))
        self.pushButtonCancel.setObjectName("pushButtonCancel")

        self.retranslateUi(DialogExpense)
        self.pushButtonCancel.clicked.connect(DialogExpense.reject) # type: ignore
        self.pushButtonSave.clicked.connect(DialogExpense.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DialogExpense)

    def retranslateUi(self, DialogExpense):
        _translate = QtCore.QCoreApplication.translate
        DialogExpense.setWindowTitle(_translate("DialogExpense", "Expense"))
        self.pushButtonSave.setText(_translate("DialogExpense", "Save"))
        self.labelExpenseName.setText(_translate("DialogExpense", "Name:"))
        self.labelExpenseAmount.setText(_translate("DialogExpense", "Amount:"))
        self.pushButtonCancel.setText(_translate("DialogExpense", "Cancel"))
