name: Pylint

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  lint-python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Get changed Python files
      id: changed-python-files
      uses: tj-actions/changed-files@v19
      with:
        files: |
          **/*.py
          **.py
        
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
      
    - name: Lint changed files
      run: |
        if [[ -z "${{ steps.changed-files-pythyon.outputs.all_changed_files }}" ]]; then
          echo "No files changed"
        else
          pylint \
          --disable=import-error    # Need Conda environment?
          ${{ steps.changed-files-python.outputs.all_changed_files }}
        fi
      


  continue-on-error: true
